version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      # Override just the host so we connect to your Windows host’s DB
      DB_SERVER: host.docker.internal